"""initial_schema

Revision ID: 40e4ffb7e95b
Revises: 
Create Date: 2026-09-07 16:04:28.342961

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40e4ffb7e95b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Human-readable name shown in the meeting UI'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Optional email — unique when present for future auth'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment="URL of the user's profile picture"),
    sa.Column('is_default_user', sa.Boolean(), nullable=False, comment='True for the seeded default application user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Internal UUID — never exposed to API clients'),
    sa.Column('meeting_id', sa.String(length=20), nullable=False, comment='Public 10-digit Zoom-like numeric ID (e.g. 8991757429)'),
    sa.Column('invite_token', sa.String(length=64), nullable=False, comment='Opaque URL-safe token for shareable invite links'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Meeting title displayed in UI'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional meeting description'),
    sa.Column('host_user_id', sa.String(length=36), nullable=True, comment='FK → users.id — nullable so record survives user deletion'),
    sa.Column('passcode', sa.String(length=20), nullable=False, comment='Meeting passcode — NEVER logged'),
    sa.Column('status', sa.Enum('scheduled', 'waiting', 'live', 'ended', 'cancelled', name='meeting_status'), nullable=False, comment='Lifecycle state — transitions validated by MeetingStateMachine'),
    sa.Column('meeting_type', sa.Enum('instant', 'scheduled', name='meeting_type'), nullable=False, comment='INSTANT or SCHEDULED'),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True, comment='Intended start time (UTC) — only set for SCHEDULED meetings'),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True, comment='Intended end time (UTC) — derived from duration'),
    sa.Column('actual_started_at', sa.DateTime(timezone=True), nullable=True, comment='When the host actually started the meeting'),
    sa.Column('actual_ended_at', sa.DateTime(timezone=True), nullable=True, comment='When the meeting was ended'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token'),
    sa.UniqueConstraint('meeting_id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('ix_meetings_host_user_id', ['host_user_id'], unique=False)
        batch_op.create_index('ix_meetings_invite_token', ['invite_token'], unique=False)
        batch_op.create_index('ix_meetings_meeting_id', ['meeting_id'], unique=False)
        batch_op.create_index('ix_meetings_scheduled_start_at', ['scheduled_start_at'], unique=False)
        batch_op.create_index('ix_meetings_status', ['status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False, comment='Opaque participant session ID of the sender'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Sender display name — denormalised for historical accuracy'),
    sa.Column('message', sa.Text(), nullable=False, comment='Chat message text — max 4000 characters enforced in service layer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Set when message is soft-deleted'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_chat_messages_meeting_id', ['meeting_id'], unique=False)

    op.create_table('meeting_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=True, comment='Opaque participant session ID — null for system events'),
    sa.Column('event_type', sa.Enum('meeting_created', 'meeting_started', 'meeting_ended', 'meeting_cancelled', 'participant_joined', 'participant_left', 'participant_removed', 'participant_muted', 'participant_unmuted', 'video_enabled', 'video_disabled', 'screen_share_started', 'screen_share_stopped', 'reaction_sent', 'chat_message_sent', 'host_changed', 'mute_all', name='meeting_event_type'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True, comment='JSON-encoded event metadata for context (display_name, role, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_events', schema=None) as batch_op:
        batch_op.create_index('ix_meeting_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_meeting_events_meeting_id', ['meeting_id'], unique=False)

    op.create_table('meeting_participants',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Internal UUID — not exposed to clients'),
    sa.Column('meeting_id', sa.String(length=36), nullable=False, comment='FK → meetings.id'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='FK → users.id — null for anonymous/guest participants'),
    sa.Column('participant_id', sa.String(length=64), nullable=False, comment='Opaque URL-safe participant ID exposed to clients and WebSocket'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Name shown in the Participants panel'),
    sa.Column('role', sa.Enum('host', 'co_host', 'participant', name='participant_role'), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False, comment='Denormalised flag for fast host checks without enum comparison'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the participant leaves or is removed'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True while the participant is in the meeting'),
    sa.Column('audio_enabled', sa.Boolean(), nullable=False),
    sa.Column('video_enabled', sa.Boolean(), nullable=False),
    sa.Column('screen_sharing', sa.Boolean(), nullable=False),
    sa.Column('hand_raised', sa.Boolean(), nullable=False),
    sa.Column('muted_by_host', sa.Boolean(), nullable=False),
    sa.Column('removed_from_meeting', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id')
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index('ix_meeting_participants_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_meeting_participants_meeting_id', ['meeting_id'], unique=False)
        batch_op.create_index('ix_meeting_participants_participant_id', ['participant_id'], unique=False)

    op.create_table('reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False, comment='Opaque participant session ID of the reactor'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Denormalised sender name for display in reaction toast'),
    sa.Column('reaction_type', sa.Enum('thumbs_up', 'clap', 'heart', 'laugh', 'surprised', 'celebrate', name='reaction_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_meeting_participants_participant_id')
        batch_op.drop_index('ix_meeting_participants_meeting_id')
        batch_op.drop_index('ix_meeting_participants_is_active')

    op.drop_table('meeting_participants')
    with op.batch_alter_table('meeting_events', schema=None) as batch_op:
        batch_op.drop_index('ix_meeting_events_meeting_id')
        batch_op.drop_index('ix_meeting_events_created_at')

    op.drop_table('meeting_events')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_meeting_id')
        batch_op.drop_index('ix_chat_messages_created_at')

    op.drop_table('chat_messages')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('ix_meetings_status')
        batch_op.drop_index('ix_meetings_scheduled_start_at')
        batch_op.drop_index('ix_meetings_meeting_id')
        batch_op.drop_index('ix_meetings_invite_token')
        batch_op.drop_index('ix_meetings_host_user_id')

    op.drop_table('meetings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
